### PR TITLE
Pass MD5 signature as 16 bytes instead of using string functions

### PR DESCRIPTION
**Pull request by jbruchon**
This converts the MD5 code in fdupes to use the MD5 digest bytes
directly instead of converting to strings and comparing with
string library functions. This significantly reduces memory
usage (each MD5 is 16 bytes instead of 33 bytes) and provides a
speedup of 7% in tests against a gcc-5.3.0 source tree.

### CODE REVIEW

**Comment by jbruchon** [comment]
Adrian, when this pull request is accepted, I'll do more work on `fdupes`. Only one modification will be requested at a time so you will have an easier time of reviewing the changes and approving them. I think this will be better than the omnibus submissions I've made previously.

**Comment by sandrotosi** [comment]
this PR is full of editorial changes (namely the tailing spaces removed) which make the review so hard and annoying I just gave up. Please resubmit with just the changes mentioned in the description (or at least split the tailing spaces removal in a different commit)

**Comment by jbruchon** [comment]
I'm not working on this anymore. I'm tired of wasting my time, and I'm tired of people whining about things like whitespace removal. @sandrotosi if you want to add to `fdupes` then feel free to do it yourself. I'm done.

**Comment by adrianlopezroche** [comment]
Jody: I appreciate the contribution, but I also understand Sandro's point
of view. I prefer to avoid commiting changes to whitespace/formatting,
despite the fact that there are aspects of formatting in fdupes I'd like to
change.

I do otherwise think it's a useful change, so I'll just add the same
functionality myself. The reason for converting hashes to strings is
historical: the earliest versions of fdupes used an external program to
calculate hashes, so I had to convert them to hex strings for compatibility
with the old approach. The use of an external program is no longer
supported, so the conversion is no longer necessary.

**Comment by jbruchon** [comment]
I understand, but there were zero formatting changes. It's a one time cleanup of ALL trailing whitespace. In any case, I'm still cutting off any further work on this project from my end. I appreciate your work to create it and your renewed efforts to enhance it. I don't appreciate people who can't spot green highlighted text and blames that on me. I'm done.

**Comment by sandrotosi** [comment]
since youre talking about me.. if it was just a one-off cleanup, that should have been done nonetheless as separate commit, as it has NOTHING to do with the proposed improvement. That's simply good programming and code management skills. it's unexpected I have to point it out explicitly, and that you consider your time more valuable that others.

**Comment by jbruchon** [comment]
To me, my time is indeed more valuable than anyone else's. When you submit code, you can submit it your way. In fact, I encourage you to do just that, particularly since you're the expert.

**Comment by sandrotosi** [comment]
good luck with your future projects!

**Comment by adrianlopezroche** [comment]
Fixed.

**Pull request closed without merging**
